config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    post 'attractions/query'
    post 'attractions/like/:id', to: 'attractions#like'
  end

  resources :itineraries
  resources :tags
  resources :attractions
  resources :places
  root to: 'home#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/attractions_controller.rb
class Api::AttractionsController < ApplicationController
  def query
    arrival = params[:arrival].to_date
    departure = params[:departure].to_date
    budget = params[:budget].to_i
    tag_ids = params[:tag_ids].map(&:to_i)
    @attractions_by_day = Attraction.query(arrival, departure, budget, tag_ids)
  end

  def like
    AttractionLike.create!(attraction_id: params[:id])

    render json: {likes: AttractionLike.where(attraction_id: params[:id]).count}
  end
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]

  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
  end

  # GET /attractions/1/edit
  def edit
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = Attraction.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:name, :duration, :travel_time, :adult_price, :adults_only, :picture, :place_id)
    end
end

app/helpers/api/attractions_helper.rb
module Api::AttractionsHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%= form_with(model: attraction, local: true) do |form| %>
  <% if attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :attraction_name %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.time_select :duration, id: :attraction_duration %>
  </div>

  <div class="field">
    <%= form.label :travel_time %>
    <%= form.time_select :travel_time, id: :attraction_travel_time %>
  </div>

  <div class="field">
    <%= form.label :adult_price %>
    <%= form.text_field :adult_price, id: :attraction_adult_price %>
  </div>

  <div class="field">
    <%= form.label :adults_only %>
    <%= form.check_box :adults_only, id: :attraction_adults_only %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :attraction_picture %>
  </div>

  <div class="field">
    <%= form.label :place_id %>
    <%= form.text_field :place_id, id: :attraction_place_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attractions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration</th>
      <th>Travel time</th>
      <th>Adult price</th>
      <th>Adults only</th>
      <th>Picture</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>
        <td><%= attraction.name %></td>
        <td><%= attraction.duration %></td>
        <td><%= attraction.travel_time %></td>
        <td><%= attraction.adult_price %></td>
        <td><%= attraction.adults_only %></td>
        <td><%= attraction.picture %></td>
        <td><%= attraction.place %></td>
        <td><%= link_to 'Show', attraction %></td>
        <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
        <td><%= link_to 'Destroy', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attraction', new_attraction_path %>

app/views/attractions/new.html.erb
<h1>New Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Back', attractions_path %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attraction.name %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @attraction.duration %>
</p>

<p>
  <strong>Travel time:</strong>
  <%= @attraction.travel_time %>
</p>

<p>
  <strong>Adult price:</strong>
  <%= @attraction.adult_price %>
</p>

<p>
  <strong>Adults only:</strong>
  <%= @attraction.adults_only %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @attraction.picture %>
</p>

<p>
  <strong>Place:</strong>
  <%= @attraction.place %>
</p>

<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>